version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2

  web1:
    image: nginx
    command: ["nginx", "-g", "daemon off;"]
    expose:
      - 80

  web2:
    image: nginx
    command: ["nginx", "-g", "daemon off;"]
    expose:
      - 80
